### PR TITLE
Prevents the map controls from submitting a form

### PR DESCRIPTION
**Pull request by anthony0030**
If a button is in a from the default behavior is to submit the form.
In my use case, I have the map in a form to set the GPS position on the entry.
When I zoom it submits the form.

https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element
Signed-off-by: Anthony Veaudry <anthony@veaudry.pro>

### CODE REVIEW

**Comment by bravecow** [comment]
@anthony0030 Thanks. Fix please eslint config (single quotes) and I will publish.

**Comment by anthony0030** [comment]
Sorry, about that.
I fixed it.

**Comment by anthony0030** [comment]
Maby adding a ```contributing.md``` file with guidelines for contributing.

**Comment by bravecow** [comment]
`mapbox-gl-controls@1.5.12` Thanks ❤️

**Comment by anthony0030** [comment]
Thank you for being so responsive :D

**Pull request merged**
